### ISSUE TITLE
Adding a register endpoint

### ISSUE THREAD

**Issue by espoirMur** [karec/cookiecutter-flask-restful#32]
I found that we have a `login` endpoint but not a `register` endpoint.

Is a register endpoint within the scope of this cookie cutter?

**Comment by karec** [comment]
Hi @espoirMur,

IMHO, a `register` endpoint is a bit out of scope for this cookiecutter, mainly because this feature is tied to project needs and, for a lot of project, external or public registration may not be a requirement, or it can rely on SSO for example.

That's why I didn't wanted to implement a registration method at first, there is a high probability that it will not fit the user needs in the end and that people will rewrite it anyway.

An option here could be an optional feature (like we have for celery) that would let the user choose if he wants it or not
