### ISSUE TITLE
Make config class instead of a plain strings

### ISSUE THREAD

**Issue by espoirMur** [karec/cookiecutter-flask-restful#37]
I have been working with this for a long time I think it should be okay to have the config as a different class one for development, another for production, and another one for testing...!

For more info check [here](https://flask.palletsprojects.com/en/1.1.x/config/#configuration-best-practices)

**Comment by karec** [comment]
Hello @espoirMur, 

Could you explain what would you put in those different classes for exemple that would different for prod / dev / testing that could not be switched with env vars ? Or maybe I misunderstood your point here

**Comment by DonalChilde** [comment]
An interesting idea, but how would you handle secrets that should not be tracked by git? Such as dB passwords... those would still need to be in a separate env file that is not tracked. A bit of a tossup as to which is better...

**Comment by espoirMur** [comment]
thanks for pointing that out @DonalChilde , we can use  a `.env` file and [python-dot env](https://github.com/theskumar/python-dotenv) package to manage them...
but the idea looks okay...

**Comment by DonalChilde** [comment]
Yeah, I wasn’t very clear. I was wondering if the added complexity was worth while, given you would still have to have an .env file for secrets. I’m leaning towards yes, but that’s mostly because I love over complication. )

**Comment by karec** [comment]
This will also depend a lot on your production environment, for example if your using containers with something like kubernetes or nomad, their is high chance that you will inject env in your containers using dedicated tools, and thus you won't need any additional file. 
And using env is in fact the recommended way of handling configuration if we follow the [12-factor app](https://12factor.net/config).  

Alternatively if you need to have mixed configuration, for example some in configuration file, other in env, and some more in a `.secrets` file, you can use dedicated librairies to handle this, like [dynaconf](https://www.dynaconf.com/)

For python-dotenv, it's already included in this cookiecutter, it's what flask use to load `.flaskenv` when using `flask` shell command, and recently I've pushed an update to also use it for loading specific test env.

If I'm not a huge fan of using different classes for config (prod / dev / tests) in this cookiecutter, it's because I'm afraid that it will push peoples forking it to put their secrets in those files, and thus putting sensible data under version control.

That's obviously and arguable point, and there is a lot of different ways to handle configuration in flask (classes, instance path, env, dedicated extensions, ...). I'm not sure we can find a "fit all situation" solution but I'm open to any proposition

**Comment by zobayer1** [comment]
Kinda agree with @karec, I like to look at config.py as a set of "default" configurations, just in case something was not covered by dot env files, or instance relative py-files.
Since we almost never interact contents of config.py in an object oriented fashion, it makes little difference to make it a class just to put the variables inside it. This also keep the application factory cleaner from writing codes that explicitly checks environment variables like FLASK_ENV to select the appropriate class reference.

**Comment by karec** [comment]
I'm closing this issue for now, feel free to re-open if needed
