### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by martgra** [karec/cookiecutter-flask-restful#38]
Ubuntu 20.04
Python 3.8 

Running pytest after creating project gives:

```bash
____________________________________________________________________________ ERROR at setup of test_revoke_access_token _____________________________________________________________________________

app = <Flask 'flaskapi'>

    @pytest.fixture
    def db(app):
        _db.app = app
    
        with app.app_context():
>           _db.create_all()

tests/conftest.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:1039: in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:1031: in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:962: in get_engine
    return connector.get_engine()
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:555: in get_engine
    options = self.get_options(sa_url, echo)
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:570: in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'NoneType' object has no attribute 'drivername'") raised in repr()] SQLAlchemy object at 0x7facf606deb0>, app = <Flask 'flaskapi'>, sa_url = None, options = {}

    def apply_driver_hacks(self, app, sa_url, options):
        """This method is called before engine creation and used to inject
        driver specific hacks into the options.  The `options` parameter is
        a dictionary of keyword arguments that will then be used to call
        the :func:`sqlalchemy.create_engine` function.
    
        The default implementation provides some saner defaults for things
        like pool sizes for MySQL and sqlite.  Also it injects the setting of
        `SQLALCHEMY_NATIVE_UNICODE`.
        """
>       if sa_url.drivername.startswith('mysql'):
E       AttributeError: 'NoneType' object has no attribute 'drivername'

venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:883: AttributeError
____________________________________________________________________________ ERROR at setup of test_revoke_refresh_token ____________________________________________________________________________

app = <Flask 'flaskapi'>

    @pytest.fixture
    def db(app):
        _db.app = app
    
        with app.app_context():
>           _db.create_all()

tests/conftest.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:1039: in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:1031: in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:962: in get_engine
    return connector.get_engine()
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:555: in get_engine
    options = self.get_options(sa_url, echo)
venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:570: in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'NoneType' object has no attribute 'drivername'") raised in repr()] SQLAlchemy object at 0x7facf606deb0>, app = <Flask 'flaskapi'>, sa_url = None, options = {}

    def apply_driver_hacks(self, app, sa_url, options):
        """This method is called before engine creation and used to inject
        driver specific hacks into the options.  The `options` parameter is
        a dictionary of keyword arguments that will then be used to call
        the :func:`sqlalchemy.create_engine` function.
    
        The default implementation provides some saner defaults for things
        like pool sizes for MySQL and sqlite.  Also it injects the setting of
        `SQLALCHEMY_NATIVE_UNICODE`.
        """
>       if sa_url.drivername.startswith('mysql'):
E       AttributeError: 'NoneType' object has no attribute 'drivername'

venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:883: AttributeError
```

**Comment by martgra** [comment]
Adding to conftest.py does the trick.
from dotenv import load_dotenv
load_dotenv('.flaskenv')

**Comment by karec** [comment]
Hello @martgra and thanks for reporting this issue.

This is mainly due to the fact that I haven't updated the readme after swapping to env variables for configuration to specify that you need to setup some variables before running pytest and that I mainly use tox myself and in the CI.

If you look in the `tox.ini` you will see that I manually setup env variables here: https://github.com/karec/cookiecutter-flask-restful/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/tox.ini#L22

Be careful using the `.flaskenv` for your tests, remember that this is your "local" configuration and tests cleanups delete tables (https://github.com/karec/cookiecutter-flask-restful/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/tests/conftest.py#L29). A simple solution could be to create a `test.env` file for exemple.


I will update the readme to reflect this and specify additional steps when using pytest directly

**Comment by martgra** [comment]
@karec I see. Well I  agree that loading .flaskenv might not be a good idea. I still think that when "testing", proper test-configuration should be passed. Perhaps like here:

```python
@pytest.fixture
def app():
    db_fd, db_path = tempfile.mkstemp()

    app = create_app({
        'TESTING': True,
        'DATABASE': db_path,
    })

    with app.app_context():
        init_db()
        get_db().executescript(_data_sql)

    yield app

    os.close(db_fd)
    os.unlink(db_path)
```
from: https://flask.palletsprojects.com/en/1.1.x/tutorial/tests/

**Comment by karec** [comment]
Downside to this solution is when you have different DB based on test env. For example:

* Using SQLite in local env to speed-up tests
* Using Postgres in CI/CD for integration tests to tests specific features (like JSON fields for example)

But we could think about something else, for example:

* Overriding configuration with testing defaults

```
@pytest.fixture
def app():
    app = create_app(testing=True)
    app.config["SQLALCHEMY_URL"] = os.getenv("SQLALCHEMY_URL", "sqlite:///:memory:")

    yield app
```

* Using a dedicated config file to override config

`test_config.py`
```
import os

SQLALCHEMY_URL = os.getenv("SQLALCHEMY_URL", "sqlite:///:memory:")
```

`app.py`

```
def create_app(testing=False, cli=False):
    """Application factory, used to create application
    """
    app = Flask("my_app")
    app.config.from_object("my_app.config")

    if testing is True:
        app.config["TESTING"] = True
        app.config.from_object("my_app.test_config")

    configure_extensions(app, cli)
    configure_apispec(app)
    register_blueprints(app)
    init_celery(app)

    return app
```

This would allow to set default values for testing without tox or env vars set for local dev but allowing us to override them based on the testing env.

What do you think ?

**Comment by Lehoczky** [comment]
Personally I prefer the `test.env` solution with defaults in `conftest.py`.

```python
@pytest.fixture
def app():
    load_dotenv("test.env")
    app = create_app(testing=True)
    app.config["SQLALCHEMY_URL"] = os.getenv("SQLALCHEMY_URL", "sqlite:///:memory:")

    yield app
```

Also we could add a default for `CELERY_TASK_ALWAYS_EAGER` here and solve #39.

Thoughts?

**Comment by karec** [comment]
This solution is simple and work well, IMHO we could even avoid redefining defaults and rely on the test env file, with a default file inside this cookiecutter and good explanations in the README.

For #39 we can prepare a `CELERY_TASK_ALWAYS_EAGER` but this won't solve the issue entirely. To allow tests to run without a rabbitMQ server we should also remove the `celery_worker` fixture. But doing so would impact peoples that actually want to test with a broker (inside docker, for CI, etc.), and this should be the default since even celery doc doesn't recommend `task_always_eager` for tests: https://docs.celeryproject.org/en/stable/userguide/testing.html#tasks-and-unit-tests

While I agree that this should be an option to simplify local dev, I need to think of a solution that would also let people use a broker to run those tests

**Comment by karec** [comment]
I've updated the README and put a `.testenv` file as @Lehoczky suggested in d2441a22dd67801f21e7c7e06049051da326d71a

I've also updated the README to include more details about testing celery, but we're not yet at the point where we can run celery without a broker out of the box, but let's discuss it on #39 

I'm closing this issue since we can now run pytest without needing to set env variables manually, feel free to re-open it if you feel that we still have work to do on that topic
