### ISSUE TITLE
The password inserted into the database when adding a user is a hash value, but it is plaintext when updating a user.

### ISSUE THREAD

**Issue by LANVNAL** [karec/cookiecutter-flask-restful#43]
I ran into this problem when I created a demo for testing using this project.Maybe it's a bug, so submit this issues.Thanks for checking out.

The password inserted into the database when adding a user is a hash value, but it is plaintext when updating a user.

post -> /api/v1/users     Add new user.The password inserted into the database when adding a user is a hash value.

PUT -> /api/v1/users/2  Update user info.The password for inserting the database is in plaintext

![](https://tmp-save.oss-cn-qingdao.aliyuncs.com/EE4E36E6-5D73-4CB1-88A7-EEF92702AFED.png)

I analyzed it for perhaps the following reasons.

The encryption process is done here, and the  `__init__`  method is executed when adding a user, but not called when updating. Maybe that's the reason.

![](https://tmp-save.oss-cn-qingdao.aliyuncs.com/Xnip2020-10-29_17-12-58.jpg)

Related Codes：
https://github.com/karec/cookiecutter-flask-restful/blob/d2441a22dd67801f21e7c7e06049051da326d71a/%7B%7Bcookiecutter.project_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/api/resources/user.py#L152-L159

https://github.com/karec/cookiecutter-flask-restful/blob/d2441a22dd67801f21e7c7e06049051da326d71a/%7B%7Bcookiecutter.project_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/api/resources/user.py#L87-L94

https://github.com/karec/cookiecutter-flask-restful/blob/d2441a22dd67801f21e7c7e06049051da326d71a/%7B%7Bcookiecutter.project_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/models/user.py#L4-L19

**Comment by karec** [comment]
Hello @LANVNAL and thanks for reporting this.

This is indeed a bug and you pin-pointed precisely the issue: `__init__` is never called by marshmallow-sqlalchemy when updating and I've hadn't added necessary logic to handle that case.

To fix this and avoid future issues with this, I've put the password hashing logic in an `hybrid_property` with an associated setter instead of putting the logic inside the endpoint itself.

I've also added a check inside the `test_put_user` 

Related [commit](https://github.com/karec/cookiecutter-flask-restful/commit/c71b8ca4011ebda60f69e4ac71330f869c7c2007)

**Comment by karec** [comment]
Issue fixed on master, I'm closing this issue. Thanks again for reporting !
